import type { Metadata } from "next";

export const metadata: Metadata = {
	title: "About Us",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<div className={`w-full h-auto`}>{children}</div>
	);
}
